### ISSUE TITLE
feedback?

### ISSUE THREAD

**Issue by sckott** [ropensci/natserv#1]
@ChristopherTracey

Any thoughts on this let me know, install like `devtools::install_github("ropenscilabs/natserv")`

**Comment by ChristopherTracey** [comment]
Wow-that was awesomely fast. Thanks!

I got it installed and such, but I seem to need an api key from NatureServe. I've tried the form, but it doesn't seem to be responding at the moment. I'll keep trying and get back to you. Thanks again!

**Comment by sckott** [comment]
there is a key in their API docs https://services.natureserve.org/BrowseServices/getSpeciesData/getSpeciesListREST.jsp you can try it with until you get yours

**Comment by ChristopherTracey** [comment]
Got it working! It looks good overall. I think I encountered one minor problem, which I'll open an issue for.

**Comment by sckott** [comment]
glad its working!

**Comment by sckott** [comment]
ill close this, keep opening new issues as they arise
