### ISSUE TITLE
some taxa failing for ns_data

### ISSUE THREAD

**Issue by sckott** [ropensci/natserv#10]
e.g., 

```r
ns_data('ELEMENT_GLOBAL.2.101998')
#> Error in which_name(xml2::xml_children(z), "subnations")[[1]] : 
#>   subscript out of bounds
```

**Comment by AnahiEspindola** [comment]
I am having the same issues with several others element IDs. Is this something that has been fixed already? Have you found any workaround?

**Comment by sckott** [comment]
thanks for the ping @AnahiEspindola can you share examples that don't work? and the errors you see

**Comment by AnahiEspindola** [comment]
I am working on trying to use ns_data() on a vector of many UIDs I'm trying to get data for. On that list, some of those UIDs actually return the information, and some others. This one (for example, there are others) is one that doesn't work: 
> ns_data(uid="ELEMENT_GLOBAL.2.882083")
Error in which_name(xml2::xml_children(z), "subnations")[[1]] : 
  subscript out of bounds

**Comment by sckott** [comment]
thanks very much. That works for me. It's possible you have the cran version https://cran.rstudio.com/web/packages/natserv/ - if you install from here `remotes::install_github("ropensci/natserv")` it should work

**Comment by sckott** [comment]
i'll get a new version to cran soon

**Comment by AnahiEspindola** [comment]
I installed from your github and it's working now. Thanks!
