### ISSUE TITLE
using natserv to find all species in a location

### ISSUE THREAD

**Issue by jamiecmontgomery** [ropensci/natserv#17]
Is there a way to define location as a way to query the Nature Serve data? I'd like to get all marine species in the Northeastern US states (NY, CT, RI, NH, ME, MA).

**Comment by sckott** [comment]
👋  thanks for your question @jafflerbach 

unfortunately not. i suppose one could query another service to get species in a particular geographic location, e.g. gbif or similar. Do you think that would work for your purposes? 

we could also ask Natureserve folks and see if there's anything they have that's not documented?

**Comment by jamiecmontgomery** [comment]
Thanks @sckott - I asked NatureServe and was told my request would cost $$ for them to provide. Fortunately I found a way around it - basically what you suggested (getting a list of species via other means and then querying the database). In the end I got what I needed!

**Comment by sckott** [comment]
thanks for asking them and glad you sorted it!
