### ISSUE TITLE
subscript out of bounds error when field is empty

### ISSUE THREAD

**Issue by ChristopherTracey** [ropensci/natserv#2]
If I try to run the following code:
`res <- ns_data(uid = 'ELEMENT_GLOBAL.2.144209')`
We get this error back: "Error in which_name(ch, "globalAbundance")[[1]] : subscript out of bounds"

This seems to happen when the 'description'  value in the globalAbundance element is empty, but 'comments' is populated as in [Scirpus ancistrochaetus](http://explorer.natureserve.org/servlet/NatureServe?sourceTemplate=tabular_report.wmt&loadTemplate=species_RptComprehensive.wmt&selectedReport=RptComprehensive.wmt&summaryView=tabular_report.wmt&elKey=150401&paging=home&save=true&startIndex=1&nextStartIndex=1&reset=false&offPageSelectedElKey=112295&offPageSelectedElType=species&offPageYesNo=true&post_processes=&radiobutton=radiobutton&selectedIndexes=112295&selectedIndexes=144336&selectedIndexes=146094&selectedIndexes=140516&selectedIndexes=150401&selectedIndexes=142153&selectedIndexes=141428&selectedIndexes=134740&selectedIndexes=144209&selectedIndexes=154689&selectedIndexes=138972&selectedIndexes=140364&selectedIndexes=132746&selectedIndexes=148188&selectedIndexes=139652&selectedIndexes=154122&selectedIndexes=142877&selectedIndexes=160492&selectedIndexes=151579&selectedIndexes=135092).  The description field for the golden eagle example is populated, and the issue is repeatable across other taxa.

**Comment by sckott** [comment]
thanks for the report, try again after reinstall `devtools::install_github("ropenscilabs/natserv")`

**Comment by ChristopherTracey** [comment]
works! thanks!

**Comment by sckott** [comment]
great, 

I expect more bugginess due to having not tested all possible data given back by natureserve - but i'll get to that soon
