### ISSUE TITLE
minor usabilty upgrade: match cases in variable names

### ISSUE THREAD

**Issue by mikeroswell** [ropensci/natserv#24]
Hi, thanks for your work on this package!

I'm playing with the results from `ns_search_spp()`, and finding variable name capitalization is inconsistent in a way that could trip me up: `"gRank"` but `"roundedGRank"`. Seems like there are nice naming conventions at work but if possible would be good to keep things consistent (always "gRank" or "GRank"). Obviously a low-priority fix!

**Comment by mikeroswell** [comment]
I see that this is not you but natureserve: https://explorer.natureserve.org/api-docs/

**Comment by dhauverNS** [comment]
@mikeroswell - Dave from NatureServe here. Property names are using camel case within the Explorer API. For the one you mentioned, "G Rank" is an abbreviation short for "Global Rank". In camel case, the full property names would be "globalRank" or "roundedGlobalRank". These get shortened to just "gRank" and "roundedGRank" when the abbreviation is used.

Hopefully this helps give a bit of context to what you're seeing.

**Comment by mikeroswell** [comment]
Hi Dave,

Thanks, I feel I need to learn about and adopt some kind of case convention in my own work, and so it's helpful to me personally to get this introduction. I appreciate you taking the time to respond, especially given I had already closed the issue! I look forward to getting to know the NatureServe team and tools better over the coming months. 

Thanks!

**Comment by sckott** [comment]
Sorry for delay, was on leave. 

Yes, I believe we retain the capitalization that NatureServe uses.  Thanks @dhauverNS for dropping in here.
