### ISSUE TITLE
Error: Internal Server Error (HTTP 500)

### ISSUE THREAD

**Issue by rsmiller74** [ropensci/natserv#28]
Error: Internal Server Error (HTTP 500) error is generated when attempting to implement the code provided in the examples.

>library('natserv')
> ns_search_comb(text = "robin", page = 0, per_page = 5)
Error: Internal Server Error (HTTP 500)
 
> ns_search_spp(species_taxonomy = list(scientificTaxonomy = "Animalia", level = "kingdom"))
Error: Internal Server Error (HTTP 500)

> ns_search_eco(ecosystem_taxonomy = "M067")
Error: Internal Server Error (HTTP 500)

> devtools::session_info()

Session info --------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/Denver
 date     2022-05-21
 rstudio  1.4.1717 Juliet Rose (desktop)
 pandoc   NA

- Packages ------------------------------------------------------------------------------------------------------------------------------------------
 package            * version    date (UTC) lib source
 assertthat           0.2.1      2019-03-21 [1] CRAN (R 4.1.1)
 bit                  4.0.4      2020-08-04 [1] CRAN (R 4.1.1)
 bit64                4.0.5      2020-08-30 [1] CRAN (R 4.1.1)
 brio                 1.1.3      2021-11-30 [1] CRAN (R 4.1.2)
 cachem               1.0.6      2021-08-19 [1] CRAN (R 4.1.1)
 callr                3.7.0      2021-04-20 [1] CRAN (R 4.1.1)
 CameraTrapDetectoR * 0.1.0      2022-05-17 [1] Github (TabakM/CameraTrapDetectoR@1a220a6)
 cameratrapR        * 0.0.0.9500 2022-04-05 [1] Github (Xinhai-Li/cameratrapR@d2e17ea)
 class                7.3-19     2021-05-03 [2] CRAN (R 4.1.1)
 classInt             0.4-3      2020-04-07 [1] CRAN (R 4.1.1)
 cli                  3.2.0      2022-02-14 [1] CRAN (R 4.1.2)
 colorspace           2.0-2      2021-06-24 [1] CRAN (R 4.1.1)
 coro                 1.0.2      2021-12-03 [1] CRAN (R 4.1.2)
 crayon               1.4.2      2021-10-29 [1] CRAN (R 4.1.2)
 crul                 1.2.0      2021-11-22 [1] CRAN (R 4.1.2)
 curl                 4.3.2      2021-06-23 [1] CRAN (R 4.1.1)
 data.table           1.14.2     2021-09-27 [1] CRAN (R 4.1.1)
 DBI                  1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
 desc                 1.4.0      2021-09-28 [1] CRAN (R 4.1.1)
 devtools             2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 digest               0.6.28     2021-09-23 [1] CRAN (R 4.1.1)
 dplyr                1.0.7      2021-06-18 [1] CRAN (R 4.1.1)
 e1071                1.7-9      2021-09-16 [1] CRAN (R 4.1.1)
 ellipsis             0.3.2      2021-04-29 [1] CRAN (R 4.1.1)
 fansi                0.5.0      2021-05-25 [1] CRAN (R 4.1.1)
 farver               2.1.0      2021-02-28 [1] CRAN (R 4.1.1)
 fastmap              1.1.0      2021-01-25 [1] CRAN (R 4.1.1)
 fs                   1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
 generics             0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
 ggplot2            * 3.3.5      2021-06-25 [1] CRAN (R 4.1.1)
 glue                 1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
 gtable               0.3.0      2019-03-25 [1] CRAN (R 4.1.1)
 hms                  1.1.1      2021-09-26 [1] CRAN (R 4.1.1)
 htmltools            0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
 httpcode             0.3.0      2020-04-10 [1] CRAN (R 4.1.1)
 httpuv               1.6.5      2022-01-05 [1] CRAN (R 4.1.2)
 jsonlite             1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
 KernSmooth           2.23-20    2021-05-03 [2] CRAN (R 4.1.1)
 labeling             0.4.2      2020-10-20 [1] CRAN (R 4.1.1)
 later                1.3.0      2021-08-18 [1] CRAN (R 4.1.1)
 lattice              0.20-44    2021-05-02 [2] CRAN (R 4.1.1)
 lifecycle            1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
 lubridate            1.8.0      2021-10-07 [1] CRAN (R 4.1.2)
 magick               2.7.3      2021-08-18 [1] CRAN (R 4.1.2)
 magrittr             2.0.1      2020-11-17 [1] CRAN (R 4.1.1)
 memoise              2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
 mime                 0.12       2021-09-28 [1] CRAN (R 4.1.1)
 munsell              0.5.0      2018-06-12 [1] CRAN (R 4.1.1)
 natserv            * 1.0.0.91   2022-05-21 [1] Github (ropensci/natserv@72acf2e)
 operators          * 0.1-8      2015-07-11 [1] CRAN (R 4.1.1)
 pillar               1.7.0      2022-02-01 [1] CRAN (R 4.1.2)
 pkgbuild             1.3.1      2021-12-20 [1] CRAN (R 4.1.2)
 pkgconfig            2.0.3      2019-09-22 [1] CRAN (R 4.1.1)
 pkgload              1.2.4      2021-11-30 [1] CRAN (R 4.1.2)
 plyr                 1.8.6      2020-03-03 [1] CRAN (R 4.1.1)
 prettyunits          1.1.1      2020-01-24 [1] CRAN (R 4.1.1)
 processx             3.5.2      2021-04-30 [1] CRAN (R 4.1.1)
 progress           * 1.2.2      2019-05-16 [1] CRAN (R 4.1.1)
 promises             1.2.0.1    2021-02-11 [1] CRAN (R 4.1.1)
 proxy                0.4-26     2021-06-07 [1] CRAN (R 4.1.1)
 ps                   1.6.0      2021-02-28 [1] CRAN (R 4.1.1)
 purrr                0.3.4      2020-04-17 [1] CRAN (R 4.1.1)
 R6                   2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
 randomForest       * 4.7-1      2022-02-03 [1] CRAN (R 4.1.3)
 rappdirs             0.3.3      2021-01-31 [1] CRAN (R 4.1.1)
 ratesci              0.4-0      2021-12-05 [1] CRAN (R 4.1.2)
 Rcpp                 1.0.7      2021-07-07 [1] CRAN (R 4.1.1)
 readr                2.1.2      2022-01-30 [1] CRAN (R 4.1.2)
 remotes              2.4.2      2021-11-30 [1] CRAN (R 4.1.2)
 reshape              0.8.8      2018-10-23 [1] CRAN (R 4.1.1)
 reshape2             1.4.4      2020-04-09 [1] CRAN (R 4.1.1)
 rlang                0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
 rprojroot            2.0.2      2020-11-15 [1] CRAN (R 4.1.1)
 rstudioapi           0.13       2020-11-12 [1] CRAN (R 4.1.1)
 sampler            * 0.2.4      2019-09-15 [1] CRAN (R 4.1.3)
 scales               1.1.1      2020-05-11 [1] CRAN (R 4.1.1)
 sessioninfo          1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
 sf                 * 1.0-3      2021-10-07 [1] CRAN (R 4.1.1)
 shiny                1.7.1      2021-10-02 [1] CRAN (R 4.1.2)
 shinyBS              0.61       2015-03-31 [1] CRAN (R 4.1.2)
 shinyFiles           0.9.1      2021-11-10 [1] CRAN (R 4.1.2)
 shinyjs              2.1.0      2021-12-23 [1] CRAN (R 4.1.2)
 sp                 * 1.4-5      2021-01-10 [1] CRAN (R 4.1.1)
 stringi              1.7.4      2021-08-25 [1] CRAN (R 4.1.1)
 stringr              1.4.0      2019-02-10 [1] CRAN (R 4.1.1)
 suncalc              0.5.0      2019-04-03 [1] CRAN (R 4.1.3)
 testthat             3.1.2      2022-01-20 [1] CRAN (R 4.1.2)
 tibble               3.1.4      2021-08-25 [1] CRAN (R 4.1.1)
 tidyr                1.2.0      2022-02-01 [1] CRAN (R 4.1.2)
 tidyselect           1.1.1      2021-04-30 [1] CRAN (R 4.1.1)
 torch                0.7.2      2022-02-25 [1] CRAN (R 4.1.3)
 torchvision          0.4.1      2022-01-28 [1] CRAN (R 4.1.2)
 torchvisionlib     * 0.1.0      2022-03-07 [1] CRAN (R 4.1.3)
 triebeard            0.3.0      2016-08-04 [1] CRAN (R 4.1.1)
 tzdb                 0.2.0      2021-10-27 [1] CRAN (R 4.1.2)
 units                0.7-2      2021-06-08 [1] CRAN (R 4.1.1)
 urltools             1.7.3      2019-04-14 [1] CRAN (R 4.1.1)
 usethis              2.1.5      2021-12-09 [1] CRAN (R 4.1.2)
 utf8                 1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
 vctrs                0.3.8      2021-04-29 [1] CRAN (R 4.1.1)
 vroom                1.5.7      2021-11-30 [1] CRAN (R 4.1.2)
 withr                2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 xtable               1.8-4      2019-04-21 [1] CRAN (R 4.1.1)

 [1] C:/Users/aprmiller/Documents/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.1/library

**Comment by dhauverNS** [comment]
Ryan, can you confirm whether this is still happening? I noticed this was submitted during a time window in which the underlying AWS search index was experiencing an outage.

**Comment by rsmiller74** [comment]
It now works as expected.  Thanks.

**Comment by maelle** [comment]
This repository is about to be archived.
