### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/natserv#29]
(or new maintainer _team_)

This package was archived on GitHub but not on CRAN.
If someone has interest in maintaining it, it won't be archived on CRAN.
We'd transfer it back to the ropensci GitHub organization.

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci-archive/admin

**Comment by ChristopherTracey** [comment]
Hi, I'm interested in taking over the maintaince of the natserv package. I work for NatureServe and its a key tool for some of our internal workflows as well as our constituents and thus we would like to see it continue. Thanks!

**Comment by maelle** [comment]
:wave: @ChristopherTracey! Thanks so much! I've transferred this repo to the rOpenSci organization and given you admin access. But actually I forgot to ask whether you wanted to keep maintaining it under the rOpenSci "umbrella"! I can transfer it to another organization if you prefer.

If you want to keep maintaining it as an rOpenSci package, here's the maintainer cheatsheet https://devdevguide.netlify.app/maintenance_cheatsheet Invitations to our Slack workspace are sent about weekly. Happy to answer any question.

**Comment by maelle** [comment]
:wave: @ChristopherTracey Happy New Year!

Would you mind updating DESCRIPTION to list you as a maintainer?
Would you like an invitation to our Slack workspace? If so at which email address? If you prefer, you can email me at `maelle@ropensci.org`. Thank you!

**Comment by ChristopherTracey** [comment]
@maelle done. Apologies for the delay.

**Comment by maelle** [comment]
No worries, thank you!!

**Comment by maelle** [comment]
@ChristopherTracey do you still maintain the package? Could you please update the README if you do? if not, we should archive the repository again. Thank you!
