### ISSUE TITLE
Species Code

### ISSUE THREAD

**Issue by ChristopherTracey** [ropensci/natserv#4]
Is the Species Code (aka ELCODE in heritage program terminology) available? Additionally, the Unique Identifier (uid) would be another useful value.

Both of these values are listed as attributes in the schema: http://services.natureserve.org/docs/schemas/biodiversityDataFlow/1/1/documentation_comprehensiveSpecies_v1.1.xml
Does that mean they are not available in the xml?

**Comment by sckott** [comment]
made a few changes, reinstall, does this do what you want:

``` r
res <- ns_data(uid = 'ELEMENT_GLOBAL.2.100925')
res[[1]]$uid
#> [1] "ELEMENT_GLOBAL.2.100925"
res[[1]]$speciesCode
#> [1] "ABNKC22010"
```

**Comment by ChristopherTracey** [comment]
Perfect! This will allow some easier linking between various NatureServe uses and other data sources.
