### ISSUE TITLE
add vignette

### ISSUE THREAD

**Issue by sckott** [ropensci/natserv#6]

**Comment by mairindeith** [comment]
Hi there - does this issue still need someone's help? I've been interested in developing R vignettes for some time, and can help out if wanted.

**Comment by sckott** [comment]
hi 👋 yes!  

have you made a vignette in an R package before? let me know either way then we can proceed from there.

**Comment by mairindeith** [comment]
Not yet, but I've read over Hadleys' guide and am quite comfortable using
Markdown. I'm hoping to learn by doing!

**Comment by sckott** [comment]
Cool. I like to have vignettes pre-built for packages that make web requests, so i just use `knitr` (and not `rmarkdown`). I've set up the structure for the vignette in the last commit, so do update before making changes. Edit the file https://github.com/ropensci/natserv/blob/master/inst/vign/natserv_vignette.Rmd and then in your command line just type `make` and it should run the vignette in `inst/vign` and move the updated version to `vignettes` dir

**Comment by mairindeith** [comment]
Will do, thanks for the clear guide. If any issues come up I'll let you know, but this seems quite straightforward.

**Comment by mairindeith** [comment]
Hey @sckott - all done! I'm just about to make a pull request to the ropensci repo containing the knit vignette.

**Comment by sckott** [comment]
done in https://github.com/ropensci/natserv/pull/16
